default:
  image: registry.gitlab.com/paddy-hack/sphinx

.dirhtml:
  artifacts:
    paths:
      - public
  except:
    - schedules

linkcheck:
  script: make -e SPHINXOPTS='--color' linkcheck

build:
  extends: .dirhtml
  cache:
    paths:
      - /opt/pipx/.cache
  before_script: pipx inject -vvv sphinx furo sphinxext-opengraph
  script: make -e SPHINXOPTS='--color' dirhtml
  after_script: mv _build/dirhtml public

pages:
  extends: .dirhtml
  stage: deploy
  variables:
    GIT_STRATEGY: none
  image: alpine
  script: >
    find public -type f -regex '.*\.\(css\|html\|ico\|js\|png\)' -exec
    gzip -k {} +
  only:
    - master
