default:
  image: registry.gitlab.com/paddy-hack/sphinx

.dirhtml:
  artifacts:
    paths:
      - public
  except:
    - schedules

linkcheck:
  before_script: pipx inject sphinx myst-parser
  script: make -e SPHINXOPTS='--color' linkcheck

build:
  extends: .dirhtml
  before_script: pipx inject sphinx furo myst-parser sphinxext-opengraph
  script: make -e SPHINXOPTS='--color' dirhtml
  after_script: mv _build/dirhtml public

pages:
  extends: .dirhtml
  stage: deploy
  variables:
    GIT_STRATEGY: none
  image: alpine
  before_script: apk add brotli
  script: >
    find public -type f -regex '.*\.\(css\|html\|ico\|js\|png\)' -exec
    brotli {} +
  only:
    - master
