image: alpine

test:
  script:
    - apk --no-cache add make python3-dev
    - pip3 install sphinx_rtd_theme
    - make dirhtml
  except:
    - master

pages:
  script:
    - apk --no-cache add make python3-dev
    - pip3 install sphinx_rtd_theme
    - make dirhtml
    - mv _build/dirhtml public
  artifacts:
    paths:
      - public
  only:
    - master
