default:
  image: registry.gitlab.com/paddy-hack/sphinx

.dirhtml:
  artifacts:
    paths:
      - public
  except:
    - schedules

build:
  extends: .dirhtml
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  before_script:
    - ls -aR .cache/pip
    - pipx inject -vvv sphinx furo sphinxext-opengraph
  script: ls -aR .cache/pip
