linkcheck:
  image: registry.gitlab.com/paddy-hack/sphinx
  script: make -e SPHINXOPTS='--color' linkcheck

build:
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  image: registry.gitlab.com/paddy-hack/sphinx
  cache:
    paths:
      - .cache/pip
  script:
    - pip3 install sphinx_rtd_theme
    - make -e SPHINXOPTS='--color' dirhtml
  after_script:
    - mv _build/dirhtml public
  artifacts:
    paths:
      - public
  except:
    - schedules

pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  image: alpine
  script:
    - find public -type f -regex '.*\.\(css\|html\|ico\|js\|png\)' -exec
      gzip -k {} +
  artifacts:
    paths:
      - public
  only:
    - master
  except:
    - schedules
